### ISSUE TITLE
Incorrect crag flag position - Chair Ladder

### ISSUE THREAD

**Issue by mkmckenna** [UKClimbing/rockfax-digital-package-issues#11]
User feedback: The area Chair Ladder is not in the correct position on the GPS map. It’s showing out to sea.

PS: Sorry, don't have permission to tag issues. "West Country Climbs"

**Comment by JimBee-JB** [comment]
This got resolved last month 
![A8B778BA-12F4-495E-8CEC-2BEBD68B4D66](https://user-images.githubusercontent.com/71782807/95647961-9dfa5680-0acb-11eb-9bc0-a14307dfd547.png)

**Comment by ryecroft** [comment]
Ah yeah, thanks for spotting that james
